# Lesson 03

# =-=-=-=-=-=-=-=-=-=-=-=-= Task 1 =-=-=-=-=-=-=-=-=-=-=-=-=
def count_matrix(motifs):
    """
    Builds a dict counting the occurences of each base at every
    position (column) across a list of motifs.
    :param motifs:
    :return:
    """

    # Finding the len() of single motif
    l = len(motifs[0])

    # Creating dict with zero-filled lists of the length[0] for each base
    counts = {
        "A": [0] * l,
        "C": [0] * l,
        "G": [0] * l,
        "T": [0] * l,
    }

    # Going through every motif seq
    for motif in motifs:
        # Going through every char and its index in the motif
        for i, base in enumerate(motif):
            # Icrement the count for that specific base at the specific position
            counts[base][i] += 1

    return counts


def score(motifs):
    """
    Calculates the score of a list of motifs. The score is the sum of the
    max counts for each columns in the count matrix.
    :param motifs:
    :return:
    """

    counts = count_matrix(motifs)
    l = len(motifs[0])
    total_score = 0

    # Looping through each column index
    for i in range(l):
        # Finding the highest count in this columns among all four bases
        max_in_column = max(counts["A"][i],
                            counts["C"][i],
                            counts["G"][i],
                            counts["T"][i])
        total_score += max_in_column

    return total_score


def consensus(motifs):
    """
    Returns the consensus string (the most freq base of
    every position in motif. Ties are resolved by picking
    the first base in the order A, C, G, T.
    :param motifs:
    :return:
    """

    counts = count_matrix(motifs)
    l = len(motifs[0])
    consensus_string = ""

    # Checking each column
    for i in range(l):
        best_base = ""
        highest_count = -1

        # Checking exactly in the A,C,G,T order -> tie breaker rule
        # Update best_base only if the count is GREATER.
        for base in "ACGT":
            if counts[base][i] > highest_count:
                highest_count = counts[base][i]
                best_base = base

        consensus_string += best_base

    return consensus_string


def hamming_distance(a, b):
    """
    Calculates the num of mismatched characters between two string of equal length.
    :param a:
    :param b:
    :return:
    """

    # Zipping (a,b) pairs up the chars of both strings side-by-side.
    # Adding 1 for every pair where the chars are not eq

    return sum(1 for char_a, char_b in zip(a,b) if char_a != char_b)


def total_distance(pattern, sequences):
    """
    For every seq, find the smallest Hamming dist between the pattern and any
    of its sliding windows, then summ minimums up.
    :param pattern:
    :param sequences:
    :return:
    """

    l = len(pattern)
    total_dist = 0

    # Processing one seq at a time
    for seq in sequences:
         # Start with infinitely high min dist
        min_dist_for_seq = float("inf")

        # Sliding the window of length 'l' across seq
        # range(len(seq) -l +1) to not go out of bounds at the end

        for i in range(len(seq) -l +1):
            window = seq[i: i+l]

            # Calculating dist between patter and the specific window
            current_dist = hamming_distance(pattern, window)

            # If the closes match so far, update record
            if current_dist < min_dist_for_seq:
                min_dist_for_seq = current_dist

        # Adding the best (minimum) dist from this eq to the total
        total_dist += min_dist_for_seq

    return total_dist


# =-=-=-=-=-=-=-=-=-=-=-=-= TASK 2 =-=-=-=-=-=-=-=-=-=-=-=-=
class MotifProfile:
    def __init__(self, motifs, pseudocount=1):
        """
        Takes a list of motifs and builds a position probability matrix (PPM).
        Uses pseudocounts to prevent zero probabilities.
        :param motifs:
        :param pseudocount:
        """

        self.l = len(motifs[0])
        t = len(motifs) # Total num of motifs

        # Reusing count_matrix func
        counts = count_matrix(motifs)

        # Initialising Position propability matrix
        self.ppm = {"A": [],
                    "C": [],
                    "G": [],
                    "T": []}

        # Calc propabilities for each base at each column
        for base in "ACGT":
            for i in range(self.l):
                # Applying the formula from read me
                # 4 represents the four possible bases
                prob = (counts[base][i] + pseudocount) / (t+4*pseudocount)
                self.ppm[base].append(prob)

    def lmer_probability(self, lmer):
        """
        Calculates the probability of a specific l-mer being
        generated by this profile. Multiplies the prob of each base
        at its respective position.
        :param lmer:
        :return:
        """

        prob = 1.0
        # Going through each base in the seq and its index
        for i, base in enumerate(lmer):
            # Multiplying the running prob by the matrix prob for this base
            prob *= self.ppm[base][i]

        return prob


    def most_probable_lmer(self, sequence):
        """
        Slides window across a seq and returns the l-mer with the
        highest probability according to the profile.
        :param sequence:
        :return:
        """

        best_prob = -1.0 # Below 0 since probs are always >=0
        best_lmer = ""

        # Sliding window of length self.l across the seq
        for i in range(len(sequence) - self.l +1):
            window = sequence[i: i + self.l]
            current_prob = self.lmer_probability(window)

            # > to automatically resolve ties by picking the
            # leftmost window (the first one that achieved the highest score)
            if current_prob > best_prob:
                best_prob = current_prob
                best_lmer = window

        return best_lmer


    def consensus(self):
        """
        Returns the consensus string built from the most
        probable base at each column
        :return:
        """

        consensus_string = ""

        for i in range(self.l):
            best_base =""
            highest_prob = -1.0

            for base in "ACGT":
                if self.ppm[base][i] > highest_prob:
                    highest_prob = self.ppm[base][i]
                    best_base = base

            consensus_string += best_base

        return consensus_string


    # =-=-=-=-=-=-=-=-=-=-=-=-= TASK 3 =-=-=-=-=-=-=-=-=-=-=-=-=
import itertools
import random
from Bio import SeqIO
from Bio import motifs
from Bio.Seq import Seq

class MotifFinder:
    def __init__(self, sequences, l, seed=None):
        """
        Initialise the finder with seqs, motif length (l), and sets
        up a private random number generator and pre-sliced sliding windows.
        :param sequences:
        :param l:
        :param seed:
        """

        self.sequences = sequences
        self.l = l
        self.rng = random.Random(42)

        # Precalculating all l-mers for every seq so repeated slicing is avoided
        self.windows = []
        for seq in sequences:
            # Creating a list of all l-mers in this spec sequence
            seq_windows = [seq[i:i+self.l] for i in range(len(seq) - self.l +1)]
            self.windows.append(seq_windows)


    def total_distance(self, pattern):
        """
        Calcs the total distance using the pre-sliced self.windows
        :param pattern:
        :return:
        """
        total_dist = 0
        for seq_windows in self.windows:
            # Find the minimum Hamming distance between the pattern and all windows in this seq
            # hamming -> from Task1
            min_dist = min(hamming_distance(pattern, w) for w in seq_windows)
            total_dist += min_dist
        return total_dist

    def median_string(self):
        """
        The EXACT algorithm: tests all 4^l possible patterns to find the one
        with the smallest total distance to our sequences.
        """
        best_distance = float('inf')
        best_pattern = ""

        # itertools.product generates all possible combinations of ACGT of length l
        for combo in itertools.product("ACGT", repeat=self.l):
            # combo is a tuple like ('A', 'C', 'G'), so we join it into a string "ACG"
            pattern = "".join(combo)
            dist = self.total_distance(pattern)

            if dist < best_distance:
                best_distance = dist
                best_pattern = pattern

        return best_pattern, best_distance

    def randomized_search(self):
        """
        The HEURISTIC algorithm: picks random starting points, builds a profile,
        and iteratively improves it until it stops getting better.
        """
        # 1. Pick a random l-mer in every sequence to form our initial motifs
        current_motifs = [self.rng.choice(seq_windows) for seq_windows in self.windows]

        # score() is reused from Task 1
        current_score = score(current_motifs)

        while True:
            # 2. Build a profile from the current motifs (pseudocount = 1)
            profile = MotifProfile(current_motifs, pseudocount=1)

            # 3. Find the most probable l-mer in every sequence using this new profile
            new_motifs = [profile.most_probable_lmer(seq) for seq in self.sequences]
            new_score = score(new_motifs)

            # 4. If the score improved, keep the new motifs and loop again.
            if new_score > current_score:
                current_motifs = new_motifs
                current_score = new_score
            else:
                # If we didn't improve, we've reached a local maximum. Stop and return.
                return current_motifs, current_score

    def best_of(self, runs):
        """
        Runs randomized_search multiple times and returns the best overall result.
        Because randomized_search can get stuck in "local maximums", restarting
        it from scratch many times improves our chances of finding the true motif.
        """
        best_motifs = []
        best_overall_score = -1

        for _ in range(runs):
            motifs, run_score = self.randomized_search()
            if run_score > best_overall_score:
                best_overall_score = run_score
                best_motifs = motifs

        return best_motifs, best_overall_score

def main():
    lecture_dna = [
        "TGACGTATAAGTTGCGATGGACGAGATAGCAGAGAATAGGCAACGAGAGATAAGCAG",
        "GACGGTAGCAGATAGACAGATGAAGAGTATGAATTGCACAGATAGCAGATAGCAGAT",
        "GGAGTGTGACGTAGCAGAGACGAAAGACGTAGAGTAGCAGTAGCAGATAGAGGGAGT",
        "TAGACAGTATAGAGACAGCGAGTCGGATAGCACCCAGTATGACGATAGCAATGACAG",
        "GCAGTAGAGCAGATTAGCATTGACAGATAGACGATTGGAGAGATGTGTGGATGACGA",
        "GGCAGGTAGCACACTGGGTCGATAAAGAGTAGCATAGAGACATAGACATATTTTAGC",
    ]

    # =-=-=-=-=-=-=-=-=-=-=-=-= TASK 1 =-=-=-=-=-=-=-=-=-=-=-=-=
    red = ["TAAGTT", "TGAATT", "GGAGTG", "CGAGTC", "TGTGTG", "TGGGTC"]  # slide 19
    best = ["AGATAG", "AGATAG", "AGATAG", "AGACAG", "AGATAG", "AGGTAG"]

    print(score(red))  # 26
    print(consensus(best), score(best))  # AGATAG 34
    print(hamming_distance("TAAGTT", "TGAATT"))  # 2
    print(total_distance("TGCGTT", lecture_dna))  # 13

    # =-=-=-=-=-=-=-=-=-=-=-=-= TASK 2 =-=-=-=-=-=-=-=-=-=-=-=-=

    profile = MotifProfile(["ATCCGTA", "GTGCATA", "AAGCGTA", "ATGCGTG"])
    print(profile.consensus())  # ATGCGTA
    print(round(profile.lmer_probability("ATGCGTA"), 4))  # 0.0122

    two = MotifProfile(["GTAC", "TTAA"])
    print(two.most_probable_lmer("ACTGGATGACCC"))  # TGAC
    print(round(two.lmer_probability("TGAC"), 4))  # 0.0093

    from Bio import motifs
    from Bio.Seq import Seq

    bio = motifs.create([Seq(site) for site in ["ATCCGTA", "GTGCATA", "AAGCGTA", "ATGCGTG"]])
    bio.pseudocounts = 1
    print(bio.consensus)  # ATGCGTA
    print(bio.pwm["A"])  # the same numbers as your profile.ppm["A"]

    # =-=-=-=-=-=-=-=-=-=-=-=-= TASK 3 =-=-=-=-=-=-=-=-=-=-=-=-=

    lecture_finder = MotifFinder(lecture_dna, 6, seed=1)

    med_pat, med_dist = lecture_finder.median_string()
    print(f"Median String: {med_pat} (Distance: {med_dist})")  # Expected: AGATAG, 2

    best_m, best_s = lecture_finder.best_of(100)
    print(f"Randomized (best of 100): {consensus(best_m)} (Score: {best_s})")  # Expected: AGATAG, 34

    # Planted motif search
    try:
        # Load sequences from the FASTA file
        planted_seqs = [str(record.seq) for record in SeqIO.parse("planted_motif.fasta", "fasta")]

        finder = MotifFinder(planted_seqs, 7, seed=42)


        print("Running median_string() ... (may take a while)")
        planted_med_pat, planted_med_dist = finder.median_string()
        print(f"Median String: {planted_med_pat} (Distance: {planted_med_dist})")

        print("Running best_of(100) ...")
        best_motifs, best_score = finder.best_of(100)
        found_consensus = consensus(best_motifs)
        print(f"Best of 100 Consensus: {found_consensus} (Score: {best_score})")
        print("Do they agree?", planted_med_pat == found_consensus)

        # Scanning with PSSM
        # Building the Biopython motif from best results
        found = motifs.create([Seq(m) for m in best_motifs])
        found.pseudocounts = 1
        pssm = found.pssm

        # Testing 1% and 0.1% False Positive Rates
        for fpr in [0.01, 0.001]:
            threshold = pssm.distribution().threshold_fpr(fpr)

            total_hits = 0
            reverse_hits = 0
            found_sites_among_them = 0

            for i, seq in enumerate(planted_seqs):
                for position, hit_score in pssm.search(Seq(seq), threshold=threshold):
                    total_hits += 1

                    if position < 0:
                        reverse_hits += 1
                    else:
                        # Checking if this forward hit is exactly the l-mer best_of() picked for this sequence
                        if seq[position:position + 7] == best_motifs[i]:
                            found_sites_among_them += 1

            print(f"FPR: {fpr} (Threshold: {threshold:.2f})")
            print(f"  Total hits: {total_hits}")
            print(f"  Reverse strand hits: {reverse_hits}")
            print(f"  Actual found sites among them: {found_sites_among_them}")

    except FileNotFoundError:
        print("Could not find 'planted_motif.fasta'. Make sure it's in the same folder!")

if __name__ == "__main__":
    main()

